### ISSUE TITLE
Setup Travis CI

### ISSUE THREAD

**Issue by odlp** [postrank-labs/postrank-uri#34]
As referenced in #33, it would be useful to setup CI with Travis. I can't add this because it requires admin privileges to the organisation (cc @igrigorik). 

<img width="674" alt="travis-screenshot" src="https://cloud.githubusercontent.com/assets/4125410/23587299/0d7d0198-01a1-11e7-85b0-332dc2d8678b.png">

---

Happy to contribute to the config once Travis CI has been enabled for this repo:
https://travis-ci.org/profile/postrank-labs

**Comment by igrigorik** [comment]
![image](https://cloud.githubusercontent.com/assets/10652/23590737/ab1babfa-0239-11e7-9525-4efada4ca1ec.png)

Done. Need to add .travis.yml..

**Comment by odlp** [comment]
All done via #36

**Comment by igrigorik** [comment]
👍
