### ISSUE TITLE
New release on RubyGems

### ISSUE THREAD

**Issue by odlp** [postrank-labs/postrank-uri#35]
Would it be possible to make a release now that #31 and #32 have been merged in? The current version on RubyGems is 1.0.18, the (unreleased?) version defined on master is 1.0.19. 

If maintainers are short on time I'd be happy to complete this, but would need to be added as a gem owner: http://guides.rubygems.org/command-reference/#gem-owner

```
gem owner postrank-uri --add <email>
```

**Comment by igrigorik** [comment]
1.0.20 should be up on rubygems. Oliver, what's your email? I'll add you as gem owner.

**Comment by odlp** [comment]
My email is `oli [\/@\/] thoughtbot.com`, thanks!

I could do with releasing `1.0.21` because unfortunately I broke the library when used with Ruby versions less than 2.4. I fixed the bug in commit https://github.com/postrank-labs/postrank-uri/commit/8eadadaa13315b18b4047549c1c07efce412d659 and in the future Travis should catch issues like this because it tests against multiple versions of Ruby.

**Comment by igrigorik** [comment]
> ... Owner could not be found.

Hmm, what's your username on rubygems?

**Comment by odlp** [comment]
Sorry @igrigorik, I still needed to sign-up with my work email. If you could try again that'd be great.

Thank you!

**Comment by igrigorik** [comment]
Ah, figures.. All done!
