### ISSUE TITLE
Allow higher versions of nokogiri?

### ISSUE THREAD

**Issue by mjankowski** [postrank-labs/postrank-uri#42]
is the current gemspec restriction required b/c of known issues with 1.9+ ... or just supplying a range out of an abundance of caution?

**Comment by igrigorik** [comment]
If memory serves, the latter. Any recommendations for min version we should set it to? If you're willing, would love to accept a PR to address this.

**Comment by mjankowski** [comment]
I can put together a PR which:

- Removes support for EOL'd rubies
- Identifies the oldest nokogiri which will works on the still supported rubies and updates gemspec for that
- Updates the Appraisals file and travis spec and so on to support those changes

I'll take a crack at that when I have a moment.

**Comment by igrigorik** [comment]
👍
